### ISSUE TITLE
what would replace register_user and delete_user calls? 

### ISSUE THREAD

**Issue by riiniii** [robinske/migrate-authy-to-verify#8]
Apologies if this was in the docs somewhere - could not find it. Also had some other questions.

- Besides calls to `Authy::Api.request_sms` and `Authy::API.verify` (thanks for the nice examples!), what would replaces calls to `Authy::Api.register_user` and `Authy::API.delete_user`? 

- I only see how to create verifications or check verifications. Does Verify API still have the notion of user? It seems like the authy_id is used to represent the authy user. It says to use the e.164 phone number instead of the authy_id. Do we now use phone numbers to uniquely identify Users in Verify and is the user created behind the scenes in Verify? 

- In order to translate Authy -> Verify, does it cost extra to use the [export api](https://www.twilio.com/docs/authy/export-api-for-authy-user-phone-numbers) to get the relevant Authy information translated to Verify API? 

- Lastly, why is it recommended to delete users when migrating to Verify? (just curious)
<img width="890" alt="Screenshot 2023-03-30 at 6 19 57 PM" src="https://user-images.githubusercontent.com/45681867/228998965-17940a18-c7f3-49b5-8417-7fea15854a51.png">

**Comment by robinske** [comment]
Hey @riiniii thanks for the q's - 

For your first two bullets:
Verify does not have the notion of a "user" like Authy did. This means there is no direct replacement for an authy_id, we use the "to" address (whether that's a phone number or email) directly in the API call and don't associate those with a user object. There is nothing to replace `register_user` or `delete_user` - you would skip this step in your application. There is no user created behind this scenes for Verify.

The export API does not cost extra, but we only enable it for customers doing the migration.

We recommend deleting Authy users to clean up your API usage and ensure a full migration.

I hope that helps! Reach out to [support](https://support.twilio.com/) if you have any other questions.
